version: '3.1'

services:

  lodetta-mongodb:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network

  lodetta-db-restore:
    depends_on:
      - lodetta-mongodb
    build: ../database
    environment:
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      FILENAME: $FILENAME
      MONGO_PORT: 27017
      HOSTNAME: lodetta-mongodb
    networks:
      - mongodb-network

networks:
  mongodb-network:
  
volumes:
  mongodb-data:


