version: '3.1'

services:

  lodetta-mongodb:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network

networks:
  mongodb-network:

volumes:
  mongodb-data:
