name: Restore DB

on:
 
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build-db-restore:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to the GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-db-restore-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-db-restore-
      -
        name: Build DB restore image
        uses: docker/build-push-action@v2
        with:
          context: database
          push: true
          tags: ghcr.io/denisiomytnysiano/lodetta-db-restore:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache